spring:
  datasource:
    url: jdbc:mysql://rm-bp10k05378cuq9109wo.mysql.rds.aliyuncs.com:3306/pangu-dev?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8
    username: pangu
    password: xfw_data@2021
    driver-class-name: com.mysql.cj.jdbc.Driver
